### ISSUE TITLE
AWS Lambda Integration not working

### ISSUE THREAD

**Issue by jdziat** [newrelic/go-agent#434]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

The current examples and documentation for enabling lambda metrics for GO based functions is not working.

## Steps to Reproduce

1. Follow implementation instructions

## Expected Behavior

Expect the invocations, traces and metrics to show in new relic

## NR Diag results

[NOTE]: # ( Provide any other relevant log data. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )
- AWS
- Serverless Framework
- Gin Adapter

## Reproduction case

[TIP]: # ( Link a sample application that demonstrates the issue. )

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by nr-swilloughby** [comment]
Hi, thanks for reaching out for assistance. Can we get a bit more information about the problem you're seeing? If you can share the code you're using to set up the instrumented functionality, or a similar mock-up example that doesn't reveal any confidential information or IP, that would be very helpful.

**Comment by jdziat** [comment]
@nr-swilloughby sure thing, meant to add more details but the day got away from me below is a similar main.go file:
```go
package main

import (
	"context"
	"fmt"
	"github.com/aws/aws-lambda-go/events"
	ginadapter "github.com/awslabs/aws-lambda-go-api-proxy/gin"
	"github.com/gin-gonic/gin"
	"github.com/newrelic/go-agent/v3/integrations/nrlambda"
	"github.com/newrelic/go-agent/v3/newrelic"
	"log"
)

var ginLambda *ginadapter.GinLambda

// Handler is the main entry point for Lambda. Receives a proxy request and
// returns a proxy response
func Handler(ctx context.Context, req events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	if ginLambda == nil {
		// stdout and stderr are sent to AWS CloudWatch Logs
		log.Printf("Gin cold start")
		r := gin.Default()
		r.GET("/lookup", lookup)
		ginLambda = ginadapter.New(r)
	}

	return ginLambda.ProxyWithContext(ctx, req)
}

func main() {
	// lambda.Start(Handler)
	app, err := newrelic.NewApplication(nrlambda.ConfigOption())
	if nil != err {
		fmt.Println("error creating app (invalid config):", err)
	}
	nrlambda.Start(Handler, app)
}

func lookup(c *gin.Context) {

	c.Status(200)
}

```
and we deploy using serverless:
```yaml
service: lambda-example
frameworkVersion: '2'
variablesResolutionMode: 20210326
provider:
  name: aws
  runtime: go1.x
custom:
  ssm: ${ssm:/aws/reference/secretsmanager/lambda-example}
functions:
  rapids:
    warmup: true
    handler: bin/lambda-example
    events:
      - http:
          path: /lookup
          method: GET
          private: true
    environment:
      GIN_MODE: ${env:GIN_MODE, 'release'}
      NEW_RELIC_ACCOUNT_ID: ${self:custom.ssm.NEW_RELIC_ACCOUNT_ID}
      NEW_RELIC_TRUSTED_ACCOUNT_KEY: ${self:custom.ssm.NEW_RELIC_TRUSTED_ACCOUNT_KEY}
      NEW_RELIC_LICENSE_KEY: ${self:custom.ssm.NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_API_KEY: ${self:custom.ssm.NEW_RELIC_API_KEY}
      NEW_RELIC_LAMBDA_EXTENSION_ENABLED: true
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: true
      NEW_RELIC_APP_NAME: 'Lambda Example'
      NEW_RELIC_LAMBDA_HANDLER: 'bin/lambda-example'

```
These are close approximations but we are not seeing any traces or metrics come over when we deploy this function.
