### ISSUE TITLE
Not able to deploy app to Elastic Beanstalk in ap-northeast-1 region with go-agent installed, hangs forever

### ISSUE THREAD

**Issue by goriunov** [newrelic/go-agent#752]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I have EB set up in Tokyo region, every time i install go-agent v3 and try to deploy golang app to the aws elastic beanstalk it just hangs on the:

```
2023-07-08 07:56:47    INFO    Deploying new version to instance(s).
```

And never progresses

Interesting enough i have no other changes except installing the newrelic go-agent. as soon as it remove go-agent and deploy without it everything works as expected.

I am not able to trace any logs for errors unfortunately. Running the app locally works as expected, i believe it could be something to do with region.

Here is my Elastic Beanstalk configurations:

```
global:
  application_name: app-name
  branch: null
  default_ec2_keyname: null
  default_platform: Go 1 running on 64bit Amazon Linux 2
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
```

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

As mentioned in the above description, create a very simple go app and deploy it to the Elastic Beanstalk in tokyo region (ap-northeast-1).

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## NR Diag results

[NOTE]: # ( Provide any other relevant log data. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

## Reproduction case

[TIP]: # ( Link a sample application that demonstrates the issue. )

## Additional context

[TIP]:  # ( Add any other context about the problem here. )
